import gpiozero
from time import sleep
from gpiozero import PWMOutputDevice
from oled_io import Oled_io
from signal import pause

green_led = gpiozero.LED(20)
yellow_led = gpiozero.LED(23)
red_led = gpiozero.LED(24)
button = gpiozero.Button(18)
buzzer = PWMOutputDevice (15)
display = Oled_io()

red_led.on()
display.print("DO NOT CROSS")

def buzz():
    buzzer.frequency = 1000
    buzzer.value = 0.5
    sleep(0.2)
    buzzer.off()
    sleep(0.8)

def button_pressed():
    print("Button pushed")
    display.print("0:15")
    buzz()
    display.print("0:14")
    buzz()
    display.print("0:13")
    buzz()
    display.print("0:12")
    buzz()
    display.print("0:11")
    buzz()
    display.print("0:10")
    buzz()
    display.print("0:09")
    buzz()
    display.print("0:08")
    buzz()
    display.print("0:07")
    buzz()
    display.print("0:06")
    buzz()
    display.print("0:05")
    buzz()
    display.print("0:04")
    buzz()
    display.print("0:03")
    buzz()
    display.print("0:02")
    buzz()
    display.print("0:01")
    buzz()
    display.print("0:00")
    buzz()
    red_led.off()
    green_led.on()
    display.print("CROSS " + "0:15")
    sleep(1)
    display.print("CROSS " + "0:14")
    sleep(1)
    display.print("CROSS " + "0:13")
    sleep(1)
    display.print("CROSS " + "0:12")
    sleep(1)
    display.print("CROSS " + "0:11")
    sleep(1)
    display.print("CROSS " + "0:10")
    sleep(1)
    display.print("CROSS " + "0:09")
    sleep(1)
    display.print("CROSS " + "0:08")
    sleep(1)
    display.print("CROSS " + "0:07")
    sleep(1)
    display.print("CROSS " + "0:06")
    sleep(1)
    display.print("CROSS " + "0:05")
    sleep(1)
    display.print("CROSS " + "0:04")
    sleep(1)
    display.print("CROSS " + "0:03")
    sleep(1)
    display.print("CROSS " + "0:02")
    sleep(1)
    display.print("CROSS " + "0:01")
    sleep(1)
    display.print("0:00")
    sleep(1)
    green_led.off()
    yellow_led.on()
    display.print("DO NOT CROSS")
    sleep(3)
    yellow_led.off()
    red_led.on()